<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/29 20:04:08
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
