default:
  http_metas:
    content-type: text/html

  metas:
    title:        VFC Control Panel
    robots:       nofollow, noindex
    description:  vfc control panel
    keywords:     none DO NOT PROCEED HERE
    language:     en

  stylesheets:    [main, themes/office_xp/office_xp.css]

  javascripts:    [jsdomenu, jsdomenubar]

  has_layout:     on
  layout:         layout
