<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/12/29 01:14:48
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
