<?php
// auto-generated by sfPhpConfigHandler
// date: 2016/12/31 05:03:45
ini_set('log_errors', '1');
ini_set('arg_separator.output', '&amp;');
if (ini_get('session.auto_start') != false)
{
  sfLogger::getInstance()->warning('{sfPhpConfigHandler} php.ini "session.auto_start" key is better set to "false" (current value is "\'0\'" - php.ini location: "/etc/php/5.6/fpm/php.ini").');
}

