# default rules
homepage:
  url:   /
  param: { module: index, action: index }

default_symfony:
  url:   /index/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
